<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Attribute' => '',
    'Module for managing goods attribute' => '',
    'Emfy' => '',
    'Content' => '',
    'Attribute list' => '',
    'Add a attribute' => '',
    'Update attribute' => '',
    'Show attribute' => '',
    'Remove attribute' => '',
    'Manage' => '',
    'Creating' => '',
    'Attributes - creating' => '',
    'Attribute admin' => '',
    'Attributes' => '',
    'creating' => '',
    'administration' => '',
    'Find attributes' => '',
    'This section describes attributes manager' => '',
    'Select {field}' => '',
    'ID' => '',
    'Name' => '',
    'Type' => '',
    'Boolean' => '',
    'String' => '',
    'Float' => '',
    'List' => '',
    'Multiple list' => '',
    'Record was added!' => '',
    'Record was removed!' => '',
    'Record was updated!' => '',
    'Fields marked with' => '',
    'are required.' => '',
    'Add attribute and continue' => '',
    'Add attribute and close' => '',
    'Save attribute and continue' => '',
    'Save attribute and close' => '',
    '--choose--' => '',
    '*unknown*' => '',
    'Page was not found!' => '',
    'Unknown request. Don\'t repeat it please!' => '',
    'Edited' => '',
    'Edition' => '',
    'Editor' => '',
    'Do you really want to remove product?' => '',
    'Attribute show' => '',
    'Value list' => '',
    'Add value' => '',
    'Add' => '',
    'Category' => '',
    'Participates in the filtration' => '',
    'Binding' => '',
    'Filtering' => '',
    'Separate values by ​​newline' => '',
    'Find a attribute' => '',
    'For goods' => '',
    'For offers' => '',
    'Target' => ''
);
