<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Attribute' => 'Aтрибуты товаров',
    'Module for managing goods attribute' => 'Модуль для управления атрибутами товаров',
    'Emfy' => 'Эмфи',
    'Content' => 'Контент',
    'Attribute list' => 'Список атрибутов',
    'Add a attribute' => 'Добавить атрибут',
    'Update attribute' => 'Изменить атрибут',
    'Show attribute' => 'Просмотр атрибута',
    'Remove attribute' => 'Удалить',
    'Manage' => 'Управление',
    'Creating' => 'Добавление',
    'Attributes - creating' => 'Атрибуты - добавление',
    'Attributes - edition' => 'Атрибуты - редактирование',
    'Attributes - view' => 'Атрибуты - просмотр',
    'Attribute admin' => 'Управление атрибутами',
    'Attributes' => 'Атрибуты',
    'creating' => 'создание',
    'administration' => 'управление',
    'Find attributes' => 'Поиск атрибутов',
    'This section describes attributes manager' => 'В данном разделе представлены средства управления атрибутами',
    'Select {field}' => 'Выберите {field}',
    'ID' => '',
    'Name' => 'Название',
    'Type' => 'Тип',
    'Boolean' => 'Логический',
    'String' => 'Строка',
    'Float' => 'Число',
    'List' => 'Список',
    'Multiple list' => 'Флажки',
    'Record was added!' => 'Запись добавлена!',
    'Record was removed!' => 'Запись удалена!',
    'Record was updated!' => 'Запись изменена!',
    'Fields marked with' => 'Поля помеченные',
    'are required.' => 'обязательны для заполнения',
    'Add attribute and continue' => 'Добавить атрибут и продолжить',
    'Add attribute and close' => 'Добавить атрибут и закрыть',
    'Save attribute and continue' => 'Сохранить атрибут и продолжить',
    'Save attribute and close' => 'Сохранить атрибут и закрыть',
    '--choose--' => '--выберите--',
    '*unknown*' => '*неизвестно*',
    'Page was not found!' => 'Страница не найдена!',
    'Unknown request. Don\'t repeat it please!' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
    'Edited' => 'Изменено',
    'Edition' => 'Изменение',
    'Editor' => 'Изменил',
    'Do you really want to remove product?' => 'Вы уверены, что хотите удалить товар?',
    'Attribute show' => 'Просмотр атрибута',
    'Value list' => 'Список значений',
    'Add value' => 'Добавить значение',
    'Add' => '',
    'Category' => 'Категория',
    'Participates in the filtration' => 'Участвует в фильтрации',
    'Binding' => 'Привязка',
    'Filtering' => 'Фильтрация',
    'Separate values by ​​newline' => 'Разделяйте значения преводом строки',
    'Find a attribute' => 'Найти атрибут',
    'For goods' => 'Для товара',
    'For offers' => 'Для предложения',
    'Target' => 'Цель'
);
